image: node:18

pipelines:
  branches:
    main:
      - step:
          name: "SSH Deploy to VPS"
          deployment: production
          script:
            - echo "🔐 Connecting to server and deploying..."
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: "root"
                SERVER: "139.162.152.133"
                COMMAND: >
                  cd /var/www/meatgrid-admin &&
                  git stash &&
                  git pull origin main &&
                  docker compose -p meatgrid-admin -f docker-compose.yml up --build -d &&
                  echo "✅ Vite app updated on server"
